### ISSUE TITLE
Missing class

### ISSUE THREAD

**Issue by cxksjy** [danyallard/Menu#1]
Can you provide the missing classes？
   VIActivation.class

**Comment by danyallard** [comment]
@cxksjy I upload it to github.

Thank you for reporting this issue

**Comment by cxksjy** [comment]
@danyallard Thank you for your prompt response！
VIActivationclass is missing a parent interface：  ClassUtilities.lvlib:Classbyref.lvclass
You may need to provide a full dependency for this awesome feature to work。

**Comment by danyallard** [comment]
@cxksjy the ClassUtilities is available at this path : https://github.com/danyallard/ClassUtilities

Hope that help resolve the problem
