### ISSUE TITLE
FrontPanel

### ISSUE THREAD

**Issue by wyxfhb** [danyallard/Menu#2]
Hello,danyallard，in your menu projiect I can't find the dependencies item which is called FrontPanel。Can you help me，where can i find the FrontPanel folder？Thank you very much。

**Comment by danyallard** [comment]
Thank you for you comment, I will commit the front panel utilities tomorrow. 

Dany

**Comment by danyallard** [comment]
I Added the Repo for the FrontPanel 
https://github.com/danyallard/FrontPanel

Let me know if you have other issue

Thank you
